project:
  type: book

book:
  title: "Quantum Theory"
  author: "Y. D. Chong"
  date: "1/31/2026"
  chapters:
    - index.qmd
    - basics.qmd
    - scattering.qmd
    - resonances.qmd
    - entanglement.qmd
    - identical_particles.qmd
    - qed.qmd
  appendices:
    - appendix_a_circular_waves.qmd
    - appendix_b_transfer_matrix.qmd
    - appendix_c_entropy.qmd
    - appendix_d_entanglement_numerics.qmd
    - appendix_e_coherent_states.qmd
    - appendix_f_anyons.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
