# Basics of Quantum Theory

Quantum theory, or quantum mechanics, is the fundamental physical
framework describing all objects of microscopic size---and, so far as
we know, larger objects too.  It was developed, in fits and starts,
over several decades in the first half of the 20th century, beginning
with [Max Planck's](https://en.wikipedia.org/wiki/Max_Planck) 1900
proposal that the energy in radiation is packaged into discrete
"quanta", and approaching its modern form with the formulation of wave
mechanics
by
[Erwin Schrödinger](https://en.wikipedia.org/wiki/Erwin_Schr%C3%B6dinger) in
1926 and matrix mechanics
by
[Werner Heisenberg](https://en.wikipedia.org/wiki/Werner_Heisenberg)
in 1928.  The mathematical formulation of quantum mechanics most
physicists use today is based on the **Dirac–von Neumann axioms**, put
together in the 1930s
by [Paul Dirac](https://en.wikipedia.org/wiki/Paul_Dirac)
and
[John von Neumann](https://en.wikipedia.org/wiki/John_von_Neumann),
which unifies and systematizes the Schrödinger and Heisenberg theories
using the mathematical language of linear algebra.

In this chapter, we review the basic principles of the theory.
This is a summary, not a pedagogical introduction; the reader is
assumed to possess some familiarity with quantum mechanics, based on
prior reading or coursework.

## States and Observables

The central idea underlying quantum theory is that there is a
distinction between **states** and **observables**.  A state describes
*how a system currently is*, while observables represent its
*measurable properties*.  In classical physics, a state may be defined
by a complete set of observables: for instance, if we know the
position and momentum of a point particle of given mass, then we know
everything about it, including the values of all other observables
(energy, orbital angular momentum, etc.).  Quantum theory, however,
draws a bright line between the two concepts.

The Dirac–von Neumann axiomatization of quantum mechanics starts with
the following postulates:

1.  **States**---A system's state is a vector $|\psi\rangle \in \mathscr{H}$, where
    $\mathscr{H}$ is a complex Hilbert space.^[A Hilbert space is a
    vector space with an inner product, plus the property of
    "completeness".  Completeness means, roughly, that infinite series
    are well-behaved: if we construct a convergent infinite sum of
    vectors from $\mathscr{H}$, the result remains in $\mathscr{H}$.
    To understand what this means, we can use an analogy with the theory of numbers.  Consider the Leibniz series for $\pi$: $$\pi =
    4\left(1-\frac{1}{3}+\frac{1}{5} - \frac{1}{7} + \cdots\right).$$ 
	The series on the right is formed from rational numbers,
    but the result of the infinite series is irrational; hence, the
    rationals do not form a complete number system.  By contrast, the
    real numbers ($\mathbb{R}$) are complete---every convergent
    infinite series of reals remains in $\mathbb{R}$.  The Hilbert
    space concept applies the same concept to vectors.]  The choice
    of Hilbert space, including its dimension, is system-specific.
  
    It is customary to subject state vectors to **normalization to
    unity**, by scaling them so that
    $$\langle \psi|\psi\rangle = 1.$$
    The reason we do this is that the rest of the theory only cares
    about the "direction" of $|\psi\rangle$, not its overall magnitude
    or phase (see postulates 3 and 4 below).

2.  **Observables**---An observable is a linear operator, $\hat{A}$,
    acting on state vectors.^[We will use hats, $\hat{\cdots}$, to
    denote operators---both Hermitian operators (observables) and
    non-Hermitian ones.] This operator is Hermitian, or self-adjoint:
    $\hat{A} = \hat{A}^{\dagger}$.  The eigenvalues correspond to the
    observable's possible measurement results.  The normalized
    eigenvectors associated with these eigenvalues are called
    **eigenstates**.

To operationalize these concepts, two further postulates are
introduced:

3.  **The Schrödinger equation**---A system's state,
    $|\psi(t)\rangle$, may vary with time $t$.  This time-dependence
    is described by an observable $\hat{H}(t)$ called the
    **Hamiltonian** (which may also be time-dependent), according to
    $$i\hbar \frac{d}{dt}|\psi(t)\rangle = \hat{H}(t) \, |\psi(t)\rangle.$$
    Note that this time-evolution is norm-preserving, or "unitary":
$\frac{d}{dt}\langle\psi(t)|\psi(t)\rangle = 0$.^[*Proof*: by
    the product rule of derivatives,
    $$\frac{d}{dt}\langle\psi(t)|\psi(t)\rangle = 
	\langle\psi(t)|\left(\frac{d}{dt}|\psi(t)\rangle\right)
	+\left(\frac{d}{dt}\langle\psi(t)|\right)|\psi(t)\rangle.$$
    The two terms are complex conjugates of each other.
    Using the Schrödinger equation, the first term becomes
    $$\frac{1}{i\hbar}\langle\psi(t)|\hat{H}(t)|\psi(t)\rangle.$$
    The second term, which is its complex conjugate, is
	$$- \frac{1}{i\hbar}\langle\psi(t)|\hat{H}^\dagger(t)|\psi(t)\rangle.$$
    If the Hamiltonian is Hermitian ($\hat{H} = \hat{H}^\dagger$), the
    two terms cancel. QED.]  We interpret $\hat{H}$ as the observable
    corresponding to the total energy of the system; its eigenvalues
    are called energy eigenvalues, or eigenenergies.

4.  **The measurement postulate**---If an observable $\hat{A}$ is
    measured on a state $|\psi\rangle$, the result is drawn
    probabilistically from one of the eigenvalues of $\hat{A}$.  The
    probability to obtain any result $a_n$, which corresponds to a
    normalized eigenstate $|n\rangle$, is given by the **Born rule**,
	$$P_n = \left|\langle n|\psi\rangle\right|^2.$${#eq-measurement}
    After the measurement, the system's state switches, or
    "collapses", to the eigenstate $|n\rangle$ matching the
    measurement outcome.
	
	Note that @eq-measurement is insensitive to the overall phase of
    the initial state: $e^{i\phi}|\psi\rangle$ (for any phase
    $\phi\in\mathbb{R}$) gives the same measurement probabilities as
    $|\psi\rangle$.  For the same reason, the post-collapse
    eigenstate's phase is also irrelevant.

From these postulates flow all the predictions of quantum mechanics,
which is possibly the most successful scientific theory of all time.
Highly-accurate quantum mechanical calculations form the basis for our
modern understanding of chemistry, materials science, nuclear physics,
and many other fields, and are crucial of the functioning of many
pieces of modern technology that we rely on everyday---lasers, LEDs,
computers, and more.

Despite these successes, however, it is possible to spot a couple of
problems lurking in the postulates:

* In postulate 3, the Schrödinger equation gives a privileged role to
  the time variable $t$.  This seems to run counter to (i) special
  relativity's demands that time and space be treated on equal
  footing, and (ii) general relativity's demands that time (and space)
  be dynamical quantities, not just passive coordinates. The first
  conflict can be resolved by a class of quantum theories called
  quantum field theories.  The second, however, remains unresolved;
  this theoretical difficulty is called the [problem of
  time](https://en.wikipedia.org/wiki/Problem_of_time).

* There is a tension between postulates 3 and 4.  Postulate 3
  describes the state evolving smoothly according to a *deterministic*
  differential equation (the Schrödinger equation).  However,
  postulate 4 describes a *probabilitic* jump to another state that
  occurs abruptly when a measurement is performed.  Thus, the act of
  measurement seems to play a special role in quantum mechanics.  This
  has surprising (and possibly troubling) consequences, as we shall
  see in @sec-chapter-entanglement.

In the remainder of this chapter, we will use the quantum postulates
to develop a few simple but important theoretical models: two-level
systems, particles on lattices, and wavefunctions.

## Two-level systems

Different quantum systems can have different state spaces.  The
simplest nontrivial complex Hilbert space is the space of
two-component complex vectors, which mathematicians denote as
$\mathbb{C}^2$.  Any vector in this space can be written as

$$|\psi\rangle = \psi_+ |+\rangle + \psi_-|-\rangle \;\;\;\leftrightarrow\;\;\;\begin{pmatrix}\psi_+ \\ \psi_-\end{pmatrix},$$

where $|+\rangle \leftrightarrow \begin{pmatrix}1\\0\end{pmatrix}$ and
$|-\rangle \leftrightarrow \begin{pmatrix}0\\1\end{pmatrix}$ are two
orthonormal basis vectors.  Here, we use $\leftrightarrow$ to denote
the representation of an abstract vector in a given basis.

### Pauli matrices {#sec-Pauli-matrices}

What observables can such a quantum system have?  Observables for
$\mathbb{C}^2$ are represented by $2\times2$ Hermitian matrices, which
are characterized by exactly four real parameters---the diagonal
elements must be real (which gives 2 independent real parameters), and
the off-diagonal elements are conjugates of each other (giving
another 2 independent real parameters).  We can write any
such matrix as

$$\hat{A} = \alpha_0 \hat{I} + \alpha_1 \hat{\sigma}_1 + \alpha_2 \hat{\sigma}_2 + \alpha_3 \hat{\sigma}_3,\;\;\;\alpha_{n} \in \mathbb{R},$$ {#eq-pauli-superposition}

where $\hat{I}$ is the $2\times2$ identity matrix, and $\sigma_1,
\dots, \sigma_3$ are the **Pauli matrices**:

$$\hat{\sigma}_1 = \begin{pmatrix}0&1\\1&0\end{pmatrix}, \,
\hat{\sigma}_2 = \begin{pmatrix}0&-i\\ i&0\end{pmatrix}, \,
\hat{\sigma}_3 = \begin{pmatrix}1&0\\ 0&-1\end{pmatrix}.$$

The identity and Pauli matrices are Hermitian (i.e., observables), so
we can regard them as a basis for constructing all other observables.
Note that these matrices are linearly independent (i.e., each cannot
be written as a linear combination of the others).  Also, the four
coefficients $\alpha_0, \dots, \alpha_3$ must be real; were we to use
a complex linear combination, the resulting operator is not guaranteed
to be Hermitian.

@eq-pauli-superposition is not the only possible basis decomposition
for the observables of $\mathbb{C}^2$, but it has some particularly
nice properties:

* The leading term, $\alpha_0\hat{I}$, represents the "trivial" part
  of the matrix.  Given any $2\times2$ Hermitian matrix $\hat{A}$, we
  can always split off such a term, with coefficient $\alpha_0 =
  \mathrm{Tr}(\hat{A})/2$.  This term has the same trace as $\hat{A}$.
  Then the remainder of the matrix (i) is traceless, and (ii)
  satisfies the following reduced eigenvalue equation:
  $$\begin{aligned}\hat{A} |\psi\rangle
  = \left(\alpha_0 \hat{I} + \alpha_1 \hat{\sigma}_1 + \alpha_2 \hat{\sigma}_2 + \alpha_3 \hat{\sigma}_3\right)|\psi\rangle &= \lambda |\psi\rangle \\
  \Rightarrow \qquad\qquad\qquad
  \left(\alpha_1 \hat{\sigma}_1 + \alpha_2 \hat{\sigma}_2 + \alpha_3 \hat{\sigma}_3\right)|\psi\rangle &= \left(\lambda - \alpha_0\right) |\psi\rangle.\end{aligned}$$
  In other words, only the Pauli matrix terms determine the form of
  the eigenstates, while $\alpha_0 = \mathrm{Tr}(\hat{A})/2$ merely
  shifts the eigenvalues (e.g., shifting the zero of energy for a
  Hamiltonian).

* Each Pauli matrix is traceless and Hermitian, and products of them
  satisfy the following multiplication table:
  $$\begin{aligned}
  \hat{\sigma}_i^2 &= \hat{I}, \;\; i=1,2,3 \\
  \hat{\sigma}_1 \hat{\sigma}_2 &= - \hat{\sigma}_2 \hat{\sigma}_2 = i\hat{\sigma}_3 \\
  \hat{\sigma}_2 \hat{\sigma}_3 &= - \hat{\sigma}_3 \hat{\sigma}_2 = i\hat{\sigma}_1 \\
  \hat{\sigma}_3 \hat{\sigma}_1 &= - \hat{\sigma}_1 \hat{\sigma}_3 = i\hat{\sigma}_2.
  \end{aligned}$$ {#eq-pauli-algebra}

  These relations constitute a so-called **Lie algebra** called the
  Pauli algebra.  They follow from a set of reasonable choices about
  how to organize a basis for $2\times2$ traceless Hermitian matrices
  (see [Exercise 1](#sec-basics-exercises)).  They can also be
  equivalently stated using the following pair of commutation and
  anticommutation relations:
  $$\begin{aligned}\left[\hat{\sigma}_i, \hat{\sigma}_j\right] &= 2i\epsilon_{ijk}\, \hat{\sigma}_k \\
  \left\{\hat{\sigma}_i, \hat{\sigma}_j\right\} &= 2\delta_{ij} \hat{I},\end{aligned}$$
  where $\epsilon_{ijk}$ is the Levi-Civita symbol.

## Wavefunctions

### Position eigenstates
Before proceeding, let us review the properties of a quantum particle
in free space.  In a $d$-dimensional space, a coordinate vector
$\mathbf{r}$ is a real vector with $d$ components.  We suppose there
is a uncountably infinite set of position eigenstates,
$\{|\mathbf{r}\rangle\}$, where each $|\mathbf{r}\rangle$ describes a
particle with a definite position $\mathbf{r}$.  The position
eigenstates are assumed to span the state space, such that the
identity operator can be resolved as

$$\hat{I} = \int d^dr \, |\mathbf{r}\rangle \langle\mathbf{r}|,$$

with the integral is taken over all allowed $\mathbf{r}$ (e.g.,
$\mathbf{r} \in \mathbb{R}^d$).  It follows that

$$\langle \mathbf{r} | \mathbf{r}' \rangle = \delta^d(\mathbf{r}-\mathbf{r}').$$

Thus, we say that the position eigenstates are *delta-normalized*,
rather than being normalized to unity.  Here $\delta^d(\cdots)$
denotes the $d$-dimensional delta function; e.g., in 2D,

$$\langle x,y \,|\, x',y' \rangle = \delta(x-x') \, \delta(y-y').$$

Moreover, the position operator $\hat{\mathbf{r}}$ is defined such
that $\hat{\mathbf{r}} |\mathbf{r}\rangle \,=\, \mathbf{r}\,
|\mathbf{r}\rangle$.

### Momentum eigenstates{#sec-momentum-eigenstates}

Momentum eigenstates are constructed from position eigenstates via
Fourier transforms.  First, let us suppose $\mathbf{r}$ runs over a
finite box of length $L$ on each side, with periodic boundary
conditions.  For plane waves of the form
$\exp(i\mathbf{k}\cdot\mathbf{r})$, where $\mathbf{k} = (k_1, \dots,
k_d)$ is the wave-vector, the periodic boundary conditions are
satisfied if and only if

$$k_j = 2\pi m/L\;\;\mathrm{for} \;m\in\mathbb{Z}.$$

Note that the set of allowed wave-vectors is discrete (i.e.,
countable), with a discretization of $\Delta k = 2\pi/L$ in each
direction.  Next, define

$$|\mathbf{k}\rangle = \frac{1}{L^{d/2}} \, \int d^dr \; e^{i\mathbf{k}\cdot\mathbf{r}} |\mathbf{r}\rangle,$$

where the integral is taken over the box.  We identify
$|\mathbf{k}\rangle$ as a momentum eigenstate, i.e., a state with
definite momentum $\hbar \mathbf{k}$.  We can now show
that

$$\langle\mathbf{k}|\mathbf{k}'\rangle = \delta_{\mathbf{k},\mathbf{k}'}, \quad \langle\mathbf{r}|\mathbf{k}\rangle = \frac{1}{L^{d/2}} e^{i\mathbf{k}\cdot\mathbf{r}}, \quad I = \sum_{\mathbf{k}} |\mathbf{k}\rangle\,\langle\mathbf{k}|.$$

In particular, note that each momentum eigenstate is normalizable to
unity.

Now let us take $L \rightarrow \infty$.  In this limit, the
wave-vector discretization $\Delta k = 2\pi / L$ goes to zero, so the
momentum eigenvalues coalesce into a continuum.  To handle this, we
redefine the momentum eigenstates as

$$|\mathbf{k}\rangle^{(\textrm{new})} = \left(\frac{L}{2\pi}\right)^{d/2} |\mathbf{k}\rangle^{(\textrm{old})}.$$

Then, by using the formula

$$\int_{-\infty}^\infty dx\; \exp(ikx) \;=\; 2\pi\, \delta(k),$$

we can show that the new momentum eigenstates are related to the
position eigenstates by

$$\begin{aligned}
  |\mathbf{k}\rangle &= \frac{1}{(2\pi)^{d/2}} \, \int d^dr \; e^{i\mathbf{k}\cdot\mathbf{r}} |\mathbf{r}\rangle, \\
  |\mathbf{r}\rangle &= \frac{1}{(2\pi)^{d/2}} \, \int d^dk \; e^{-i\mathbf{k}\cdot\mathbf{r}} |\mathbf{k}\rangle. \end{aligned}$$
  
Position and momentum are now treated on similar footing, with the
integrals over $\mathbf{r}$ and $\mathbf{k}$ both taken over infinite
spaces.  Moreover, the momentum eigenstates now satisfy

$$\begin{aligned}
  I &= \int d^dk \;|\mathbf{k}\rangle\,\langle\mathbf{k}|, \label{Iresolk} \\
  \langle\mathbf{k}|\mathbf{k}'\rangle &= \delta^d(\mathbf{k}-\mathbf{k}'), \\
  \langle\mathbf{r}|\mathbf{k}\rangle &= \frac{e^{i\mathbf{k}\cdot\mathbf{r}}}{(2\pi)^{d/2}}.\end{aligned}$$
  
The first two equations are analogous to their position eigenstate
counterparts.  In particular, the new $|\mathbf{k}\rangle$'s are
delta-normalized.  The last equation can be interpreted as the
wavefunction of the delta-normalized momentum eigenstate.

The momentum operator $\hat{\mathbf{p}}$ is defined using the
$|\mathbf{k}\rangle$'s as the eigenbasis:

$$ \hat{\mathbf{p}} |\mathbf{k}\rangle \,=\, \hbar \mathbf{k}\,
|\mathbf{k}\rangle.$$

For any quantum state $|\psi\rangle$, whose wavefunction is
$\psi(\mathbf{r}) = \langle \mathbf{r}|\psi\rangle$, we can show that
the momentum operator acts on wavefunctions in the following way:

$$\begin{aligned}\langle \mathbf{r}|\hat{\mathbf{p}}|\psi\rangle
  &= \frac{1}{(2\pi)^{d/2}} \, \int d^dk \; e^{i\mathbf{k}\cdot\mathbf{r}} \langle \mathbf{k} | \hat{\mathbf{p}} | \psi\rangle \\
  &= \frac{1}{(2\pi)^{d/2}} \, \int d^dk \; \hbar\mathbf{k} \, e^{i\mathbf{k}\cdot\mathbf{r}} \langle \mathbf{k} | \psi\rangle \\
  &= -i \hbar\nabla \left[\frac{1}{(2\pi)^{d/2}} \, \int d^dk \, e^{i\mathbf{k}\cdot\mathbf{r}} \langle \mathbf{k} | \psi\rangle \right] \\
  &= -i\hbar \nabla\psi(\mathbf{r}).
  \end{aligned}$$

## Exercises {#sec-basics-exercises}

1. In this exercise, we work through a line of reasoning that gives
   rise to the Pauli matrix algebra, @eq-pauli-algebra.  We begin with
   the observation that $2\times2$ Hermitian matrices are
   characterized by four real parameters (see @sec-Pauli-matrices).
   After splitting off a term
   $\frac{1}{2}\mathrm{Tr}(\hat{A})\,\hat{I}$, which does not affect
   the eigenvectors, we are left with traceless Hermitian matrices
   characterized by three real parameters.  We thus seek a linear
   decomposition
   $$\alpha_1 \hat{\sigma}_1 + \alpha_2 \hat{\sigma}_2 + \alpha_3 \hat{\sigma}_3,\;\; \alpha_i \in \mathbb{R},$$
   where each $\hat{\sigma}_i$ is some traceless Hermitian matrix.

    A. Explain why we may choose each $\hat{\sigma}_i$
    so that its eigenvalues are $\{1, -1\}$.
	
    B. Prove that each matrix therefore satisfies $\hat{\sigma}_i^2 = \hat{I}$.

    C. Consider the commutator between any two of these matrices,
	$$[\hat{\sigma}_i, \hat{\sigma}_j] = \hat{\sigma}_i \hat{\sigma}_j - \hat{\sigma}_j \hat{\sigma}_i, \;\;\;i\ne j.$$
    Explain why this is automatically (i) traceless, and (ii)
    anti-Hermitian (i.e., $i$ times some Hermitian matrix).

2. In @sec-momentum-eigenstates, we derived the eigenstates of a
particle in an empty infinite space by considering a box of length
$L$ on each side, applying periodic boundary conditions, and taking
$L \rightarrow \infty$.  Suppose we instead use Dirichlet boundary
conditions (i.e., the wavefunction vanishes on the walls of the
box).  Show that this gives rise to the same set of momentum
eigenstates in the $L \rightarrow \infty$ limit.
